### PR TITLE
Drop support for deprecated WMS service

### LINKED ISSUE #61: Remove all WMS functionality and services from the tool
WMS is an old standard and is due to be turned off in the LDS in Aug/Sep 2020.

### PR DESCRIPTION
**Pull request by strk**
Closes #61

### CODE REVIEW

**Comment by strk** [comment]
CI fails due to an unrelated issue, reported in #63

**Comment by SPlanzer** [comment]
Looks good to me - The application should also be simplified. This is as the application was made overly complicated due to the WMS server taking up to 3-4min to respond to getCapabilities request from WMS at times. This required caching to be build which complicated the src code and double the size of the application. 

now we are not using WMS and do not need to handle the server bug I recommend a refactor to remove all caching.

**Review by SPlanzer — APPROVED** [review]

**Comment by SPlanzer** [comment]
Having a very frustrating time with this. GH conflict tool is failing. Im not using to editing forked pull requests and am having issues with editing this locally. 

I have tested changes locally and with updated tests that pass CI.

@strk can you either get this merged to master as is, else I will cherry pick what i require from this into my own branch

**Comment by strk** [comment]
You should stop running code formatters...  I'll take care of conflicts resolution and merge

**Pull request merged**
