### PR TITLE
Wfs fetch limit

### LINKED ISSUE #89: WFS: Add option to fetch data for the given map canvas extent
This will allow large datasets like parcels to be added to a project. At the moment the WFS connection string will force the whole dataset to be cached first before it can be used correction in the project. In the case of NZ Parcels that's over 5GB of data. Adding these options will allow the user to request data within the viewable map window.

You can achieve this by adding the WFS provider options `restrictToRequestBBOX=1 and pagingEnabled='true'`

Not sure if this should be the main method or a user option. In some cases the user might want to see all the data in the layer table (vs just the current extent), so it's probabily best to provide an option for this.

### PR DESCRIPTION
**Pull request by billgeo**
Simplest fix to close #89 

~~Also, had to change how layers are loaded by default to enable integration test. They are now loaded 'unchecked'. While, this is different to normal QGIS behaviour, I think this makes sense when loading large WFS layers.~~

This is my first QGIS UI test, so I'm sure there's lots to improve there. Would appreciate feedback on that.

To test:

Integration test commit https://github.com/linz/linz-data-importer/commit/7f95edefbfea71b1a63c6165ca0406060c37c174 : test should fail
Restrict to extent of map window commit https://github.com/linz/linz-data-importer/commit/8990f85b8b19a7b0cd5cf49839713b092a8a73cc : test should pass

### CODE REVIEW

**Comment by billgeo** [comment]
1. Updated to use `restrictToRequestBBOX=1` which is the officially supported parameter.
2. Undid change to not render layers by default after discussion with @SPlanzer 
3. Fixed a test that broke.

**Review by SPlanzer — APPROVED** [review]
LTGM

I would like to see the UX as a result of these changes but this plugin results in a mem alloc error for me. I am yet to find anyone else that has this issue. For this reason it would be good if I can come by for a visit prior to closing this to discuss UX

**Comment by SPlanzer** [comment]
We will also need to update the change log as part of a release

**Comment by billgeo** [comment]
Thanks @SPlanzer . Will grab you tomorrow if you're around. Might be worth raising an issue for the mem alloc problem.

**Pull request merged**
