### PR TITLE
Add test for basemaps layer

### PR DESCRIPTION
**Pull request by strk**
Allow for testing multiple layers per service, add
a basemap WMTS layer import test

### CODE REVIEW

**Comment by strk** [comment]
I don't know why Travis tests are not running. I'd expect them to fail due to lack of API key (`LDI_BASEMAPS_KEY` shall be added to secrets). Ideas @SPlanzer ? Can you add that secret ?

**Comment by strk** [comment]
I see Travis now did run, it must have been just very slow at starting

**Comment by SPlanzer** [comment]
> I'd expect them to fail due to lack of API key (LDI_BASEMAPS_KEY shall be added to secrets). Ideas @SPlanzer ? Can you add that secret ?

Which key are we using?. I understand we can get one from the base-maps website but this is rotated. Do we have a key that will not be rotated on us? 

If you sign in to the travis pro utility you can add the secrets to the travis.yml - see https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables.

Else let me know the API key and I can add it.

**Comment by strk** [comment]
Indeed all tests are failing, looks like (no layers are loaded). I'm using #75 to debug this

**Comment by strk** [comment]
I'm getting an invalid API key. Is it normal that every `travis encrypt` command produces a different `secret` value ?

**Comment by strk** [comment]
I don't know how to proceed here. The encryption of secret seems to fail. The key works for my on my local qgis install, but doesn't seem to get recognized as valid in Travis testing. Any hint @SPlanzer ?

**Comment by SPlanzer** [comment]
> I don't know how to proceed here. The encryption of secret seems to fail. The key works for my on my local qgis install, but doesn't seem to get recognized as valid in Travis testing. Any hint @SPlanzer ?


Are you using travis pro. This requires you to sign in using the travis pro utility in the terminal. I have add such issue when using just standard travis and not travis pro. 

difficulties with Travis encryption is a good reason move to github actions

**Comment by strk** [comment]
I'm using the CLI, I've done:
> travis login --pro --auto
Successfully logged in as strk!
> travis encrypt --pro LDI_BASEMAPS_KEY="$APIKEY" --add

**Comment by strk** [comment]
Figured: I was failing to pass the new environment to docker ! This is ready to merge

**Review by SPlanzer — COMMENTED** [review]
LGTM

**Pull request merged**
