### PR TITLE
WIP: use github-action

### PR DESCRIPTION
**Pull request by strk**
Instead of travis..

### CODE REVIEW

**Comment by strk** [comment]
I need some keys to store as secrets. @SPlanzer I've added the basemap one, which I obtained, but I'm missing the other 3, do you have them handy ?

**Comment by strk** [comment]
Nevermind, I had Travis encode those key for me and print them (and added them as secrets in github-actions)

**Review by SPlanzer — APPROVED** [review]
Tests are passing looks good to me

**Comment by SPlanzer** [comment]
Thank you @strk. This makes me very happy.

**Comment by billgeo** [comment]
Great! Thanks @strk.

**Pull request merged**
